# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (frontend & backend)
on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
jobs:
  build:
    name: Build â€¢ ${{ matrix.app.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        app:
          - name: frontend
            path: frontend
          - name: backend
            path: backend
            
    defaults:
      run:
        working-directory: ${{ matrix.app.path }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'          
          # point cache to the correct lockfile under each subfolder
          cache-dependency-path: ${{ matrix.app.path }}/package-lock.json

      - name: Instal deps
        run: npm install; npm ci

      - name: Test
        run: npm test --passWithNoTests

      - name: Build
        run: npm run build --if-present

      
      # optional: upload build artifacts per app
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app.name }}-build
          path: ${{ matrix.app.path }}/build
